import { IDatabase, ITable } from '@aws-cdk/aws-glue-alpha';
import { IGrantable, Grant } from 'aws-cdk-lib/aws-iam';
import { IBucket } from 'aws-cdk-lib/aws-s3';
import { CodeFragment } from './codenizer';
import { IGranter, NodeBase } from './node';

/**
 * Props of CatalogTarget.
 */
export interface CatalogTargetProps {
  /**
   * The database that contains the table you want to use as the target.
   * This database must already exist in the Data Catalog.
   */
  readonly database: IDatabase;
  /**
   * The table that defines the schema of your output data.
   * This table must already exist in the Data Catalog.
   */
  readonly table: ITable;
  /**
   * The name of the data target.
   *
   * @default 'AWS Glue Data Catalog'
   */
  readonly name?: string;
  /**
   * Granter the necessary authorization to a node.
   */
  readonly granter?: IGranter;
}

/**
 * Specifies a data target that writes to AWS Glue Data Catalog using the Glue Data Catalog.
 */
export class CatalogTarget extends NodeBase {
  readonly database: IDatabase;
  readonly table: ITable;
  private readonly granter?: IGranter;
  constructor(id: string, props: CatalogTargetProps) {
    super(id, props.name ?? 'AWS Glue Data Catalog');
    this.database = props.database;
    this.table = props.table;
    this.granter = props.granter;
  }

  python(): CodeFragment {
    if (this.inputs.length !== 1) {
      throw new Error(
        `The catalog target node used to require one input node, but now there are ${this.inputs.length} input nodes available.`
      );
    }
    const code = [
      `# Script generated by CDK for node ${this.name}`,
      `${this.nodeId} = glueContext.write_dynamic_frame.from_catalog(`,
      `    frame=${this.inputs[0].nodeId},`,
      `    database="${this.database.databaseName}",`,
      `    table_name="${this.table.tableName}",`,
      `    transformation_ctx="${this.nodeId}",`,
      `)`,
    ].join('\n');
    return {
      body: [code],
    };
  }
  scala(): CodeFragment {
    throw new Error('Method not implemented.');
  }
  grant(job: IGrantable): Grant | undefined {
    return this.granter?.grant(job);
  }
}

/**
 * Props of S3CatalogTarget.
 */
export interface S3CatalogTargetProps {
  /**
   * The database that contains the table you want to use as the target.
   * This database must already exist in the Data Catalog.
   */
  readonly database: IDatabase;
  /**
   * The table that defines the schema of your output data.
   * This table must already exist in the Data Catalog.
   */
  readonly table: ITable;
  /**
   * The bucket of table.
   */
  readonly bucket: IBucket;
  /**
   * The name of your data source.
   *
   * @default 'Amazon S3'
   */
  readonly name?: string;
}

/**
 * Specifies a data target that writes to Amazon S3 using the Glue Data Catalog.
 */
export class S3CatalogTarget extends CatalogTarget {
  constructor(id: string, props: S3CatalogTargetProps) {
    super(id, {
      database: props.database,
      table: props.table,
      name: props.name ?? 'Amazon S3',
      granter: {
        grant(job) {
          return props.bucket.grantWrite(job);
        },
      },
    });
  }
}

/**
 * Data targets.
 */
export class DataTarget {
  /**
   * Create a new {@link CatalogTarget}.
   */
  static catalog(id: string, props: CatalogTargetProps) {
    return new CatalogTarget(id, props);
  }
  /**
   * Create a new {@link S3CatalogTarget}.
   */
  static s3Catalog(id: string, props: S3CatalogTargetProps) {
    return new S3CatalogTarget(id, props);
  }
}
