import { IGrantable, Grant } from 'aws-cdk-lib/aws-iam';
import { CodeFragment } from './code-builder';
import { NodeBase } from './node';

/**
 * Props of DropFields.
 */
export interface DropFieldsProps {
  /**
   * Field you want to drop.
   */
  readonly fields: string[];
  /**
   * Name of node.
   *
   * @default 'Drop Fields'
   */
  readonly name?: string;
}

/**
 * Transform of Drop Fields.
 */
export class DropFields extends NodeBase {
  private readonly fields: string[];
  constructor(id: string, props: DropFieldsProps) {
    super(id, props.name ?? 'Drop Fields');
    this.fields = props.fields;
  }

  python(): CodeFragment {
    if (this.inputs.length !== 1) {
      throw new Error(
        `The drop field node used to require one input node, but now there are ${this.inputs.length} input nodes available.`
      );
    }
    const code = [
      `# Script generated by CDK for node ${this.name}`,
      `${this.nodeId} = DropFields.apply(`,
      `    frame=${this.inputs[0].nodeId},`,
      `    paths=${JSON.stringify(this.fields)},`,
      `    transformation_ctx="${this.nodeId}",`,
      `)`,
    ].join('\n');
    const parent = this.inputs[0].python();
    return {
      imports: parent.imports,
      body: [...parent.body, code],
    };
  }
  scala(): CodeFragment {
    throw new Error('Method not implemented.');
  }
  grant(_grantee: IGrantable): Grant | undefined {
    return undefined;
  }
}

/**
 * Transforms.
 */
export class Transform {
  /**
   * Create a new {@link DropFields}.
   */
  static dropFields(nodeId: string, props: DropFieldsProps) {
    return new DropFields(nodeId, props);
  }
}
