import { App, Stack } from 'aws-cdk-lib';
import { Role, ServicePrincipal } from 'aws-cdk-lib/aws-iam';
import { Transform } from '../../src';
import { SomeNode } from '../node.test';

describe('SelectFields', () => {
  test('Must be able to specify name', () => {
    const defaultName = Transform.selectFields('node1', {
      fields: ['fields'],
    });
    const specifyName = Transform.selectFields('node2', {
      name: 'Specify Name',
      fields: ['fields'],
    });
    expect(defaultName.name).toBe('Select Fields');
    expect(specifyName.name).toBe('Specify Name');
  });

  test('If not provide granter and grant then not throw error', () => {
    const app = new App();
    const stack = new Stack(app, 'MyStack');
    const selectFields = Transform.selectFields('node1', {
      fields: ['fields'],
    });
    selectFields.grant(
      new Role(stack, 'Role', {
        assumedBy: new ServicePrincipal('glue.amazonaws.com'),
      })
    );
  });

  test('No inputs and build then python throw error', () => {
    const selectFields = Transform.selectFields('node1', {
      fields: ['fields'],
    });
    expect(() => selectFields.python()).toThrow(
      'You need to choose exactly 1 parent(s) for SelectFields Transform.'
    );
  });

  test('2 inputs and build then python throw error', () => {
    const selectFields = Transform.selectFields('node1', {
      fields: ['fields1', 'fields2'],
    });
    new SomeNode('Input1').to(selectFields);
    new SomeNode('Input2').to(selectFields);
    expect(() => selectFields.python()).toThrow(
      'You need to choose exactly 1 parent(s) for SelectFields Transform.'
    );
  });

  test('Python should build code', () => {
    const selectFields = Transform.selectFields('node1', {
      fields: ['fields1', 'fields2'],
    });
    const prevNode = new SomeNode('prev_node');
    prevNode.to(selectFields);
    const code = selectFields.python();
    expect(code.imports).toBeUndefined();
    expect(code.head).toBeUndefined();
    expect(code.body).toStrictEqual([
      `# Script generated by CDK for node Select Fields
SelectFields_node1 = SelectFields.apply(
    frame=SomeNode_prev_node,
    paths=["fields1","fields2"],
    transformation_ctx="SelectFields_node1",
)`,
    ]);
    expect(code.tail).toBeUndefined();
  });

  test('Scala not implement', () => {
    const selectFields = Transform.selectFields('SelectFields', {
      fields: ['fields1', 'fields2'],
    });
    const prevNode = new SomeNode('prev_node');
    prevNode.to(selectFields);
    expect(() => selectFields.scala()).toThrow();
  });
});
