import { Column } from '@aws-cdk/aws-glue-alpha';
import { IGrantable, Grant } from 'aws-cdk-lib/aws-iam';
import { CodeFragment } from '../code-builder';
import { NodeBase } from '../node';

/**
 * Apply Mapping field.
 */
export interface ApplyMappingField {
  /**
   * Source field.
   */
  readonly source: Column;
  /**
   * Target field.
   */
  readonly target: Column;
}

/**
 * Props of ApplyMapping.
 */
export interface ApplyMappingProps {
  /**
   * Field you want to select.
   */
  readonly mappings: ApplyMappingField[];
  /**
   * The node name.
   *
   * @default 'Apply Mapping'
   */
  readonly name?: string;
}

/**
 * Map fields to new names and types of your chice.
 */
export class ApplyMapping extends NodeBase {
  private readonly mappings: ApplyMappingField[];
  constructor(id: string, props: ApplyMappingProps) {
    super(id, props.name ?? 'Apply Mapping');
    this.mappings = props.mappings;
  }

  python(): CodeFragment {
    if (this.inputs.length !== 1) {
      throw new Error(
        `You need to choose exactly 1 parent(s) for ApplyMapping Transform. Now ${this.inputs.length} parent(s).`
      );
    }
    // [`("hoge", "string", "column2", "string")`, `("fuga", "string", "column1", "string")`]
    const records = this.mappings
      .map((m) =>
        [
          m.source.name,
          m.source.type.inputString,
          m.target.name,
          m.target.type.inputString,
        ]
          .map((v) => `"${v}"`)
          .join(', ')
      )
      .map((m) => `(${m})`);
    const code = [
      `# Script generated by CDK for node ${this.name}`,
      `${this.nodeId} = ApplyMapping.apply(`,
      `    frame=${this.inputs[0].nodeId},`,
      `    mappings=[`,
      records.map((record) => `        ${record},`).join('\n'),
      `    ],`,
      `    transformation_ctx="${this.nodeId}",`,
      `)`,
    ].join('\n');
    return {
      body: [code],
    };
  }
  scala(): CodeFragment {
    throw new Error('Method not implemented.');
  }
  grant(_job: IGrantable): Grant | undefined {
    return undefined;
  }
}
